spring.application.name=demo

# ===================================
# PostgreSQL + Hibernate (JPA) - NeonTech (CORREGIDO)
# ===================================

# Usando tu host real: ep-flat-paper-am1dl3iw-pooler
spring.datasource.url=jdbc:postgresql://ep-flat-paper-am1dl3iw-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SR6qGT4BimLl
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect